language: node_js

node_js:
  - "5"

before_install:
  - openssl aes-256-cbc -K $encrypted_7b7fa87d9957_key -iv $encrypted_7b7fa87d9957_iv -in .travis/id_travis.enc -out ~\/.ssh/id_rsa -d
# Set the permission of the key
  - chmod 600 ~/.ssh/id_rsa
# Start SSH agent
  - eval $(ssh-agent)
# Add the private key to the system
  - ssh-add ~/.ssh/id_rsa
# Copy SSH config
  - cp .travis/ssh_config ~/.ssh/config
# Set Git config
  - git config --global user.name "boogoofrog"
  - git config --global user.email "boogoofrog@gmail.com"
# Install Hexo
  - npm install hexo-cli -g
  - npm install hexo --save
  - npm install
  - npm install hexo-generator-feed --save
  - npm install hexo-deployer-git --save
  - npm install hexo-renderer-ejs --save
  - npm install hexo-renderer-stylus --save
  - npm install hexo-renderer-marked --save
  - npm install hexo-renderer-sass --save
# Clone the repository
  - git clone https://github.com/boogoofrog/boogoofrog.github.io -b gh-pages --single-branch .deploy_git

  script:
  - hexo generate
  - hexo deploy

branches:
  only:
    - master
