language: node_js
node_js:
  - '5'
before_install:
  - touch ~/.ssh/id_rsa
  - openssl aes-256-cbc -K $encrypted_7b7fa87d9957_key -iv $encrypted_7b7fa87d9957_iv-in .travis/id_travis.enc -out ~\/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - eval $(ssh-agent)
  - ssh-add ~/.ssh/id_rsa
  - cp .travis/ssh_config ~/.ssh/config
  - export TZ=Asia/Taipei
  - npm install hexo-cli -g
  - npm install
before_script:
  # Set Git config
  - git config --global user.name "boogoofrog"
  - git config --global user.email boogoofrog@gmail.com
  - git config --global push.default simple
script:
  - hexo g
after_success:
  - hexo deploy
branches:
  only:
  - hexo-source
cache:
  directories:
  - node_modules