language: node_js
node_js:
  - "5"

before_install:
  - git config --global push.default matching
  - git config --global user.name "boogoofrog"
  - git config --global user.email boogoofrog@gmail.com
  - sed -i'' "/^ *repo/s~github\.com~${DEPLOY_REPO}@github.com~" _config.yml

install:
  - npm install hexo-cli -g
  - npm install hexo --save
  - npm install

script:
  - hexo clean
  - hexo generate

after_success:
  - hexo deploy

branches:
  only:
    - gh-pages
    
cache:
  directories:
    - node_modules
