language: node_js
node_js:
- "5"  # nodejs的版本
branches:
  only:
  - gh-pages  

before_install:
- git config --global push.default matching
- git config --global user.name "boogoofrog"
- git config --global user.email "boogoofrog@gmail.com"
- sed -i'' "/^ *repo/s~github\.com~${DEPLOY_REPO}@github.com~" _config.yml


install:
  - npm install hexo-cli -g
  - npm install hexo --save
  - npm install
  - npm install hexo-generator-feed --save
  - npm install hexo-deployer-git --save
  - npm install hexo-renderer-ejs --save
  - npm install hexo-renderer-stylus --save
  - npm install hexo-renderer-marked --save
  - npm install hexo-renderer-sass --save

script:
  - hexo clean
  - hexo d -g --silent

cache:
  directories:
    - node_modules