menu:
    Blog: /
    Archive: /archives/
    Facebook: https://www.facebook.com/yunian.chen
    GitHub: https://github.com/boogoofrog
    Linkedin: https://www.linkedin.com/in/richi-yu-nien-chen-4989a07a
    Rss: /atom.xml

favicon: /favicon.png
logo: /favicon.png

# Comment
disqus: boogoofrog
duoshuo: 

# Analytics
# google-analytics:
ga: UAd-78533039-1

# Copyright Infomation
startyear: 2016

# Font CDN
#true : use google fonts api, not stable for chinese visitor sometimes, caused by force majeure factor
#false: use useso fonts api instead of google's, great response speed for chinese visitor
googlefonts: false

language: zh-tw
